INTERNAL_ERROR = "Error: Internal error"
USAGE_LIMIT_EXCEEDED_ERROR = "Error: Usage limit exceeded"
NO_IMPORT_SELECTED = "Error: No import option selected"
CONVERSATION_NOT_FOUND = "Error: Conversation not found"
VERSION_DOES_NOT_EXISTS = "Error: Requested version does not exist in S3 bucket"
COLLECTION_NOT_FOUND = "Error: Requested collection was not found"
CONTENT_ARCHIVED_MESSAGE = "content archived for space saving purposes"
